database:
    image: mysql:5.7
    volumes:
        - dbdata:/var/lib/mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: desafioapi
        MYSQL_USER: default
        MYSQL_PASSWORD: secret
    ports:
        - "33061:3306"
